---

- name: restart patroni-watchdog
  systemd:
    name: patroni-watchdog
    state: restarted
    daemon_reload: yes
    enabled: yes
  notify:
    - stop watchdog

- name: stop watchdog
  systemd:
    name: watchdog
    state: stopped
    enabled: yes
  notify:
    - start watchdog

- name: start watchdog
  systemd:
    name: watchdog
    state: started
    enabled: yes

- name: restart patroni
  systemd:
    name: patroni.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart haproxy
  systemd:
    name: haproxy.service
    state: restarted
    daemon_reload: yes
    enabled: yes
